filename = "https://drive.google.com/uc?export=download&id=1Fv_vhoN4sTrUaozFPfzr0NCyHJLIeXEA"

import time
import pandas as pd
import numpy as np
import pyarrow
import openpyxl

pd.set_option('display.max_columns', None)  # Show all columns in the output


def load_csv(filepath): # defining a function to load a CSV file from a given filepath
    print(f"Loading data from {filepath}...") # telling the user that the file is being loaded
    start_time = time.time() # records start time
    try:
        df = pd.read_csv(filepath, engine='python')  
            # reads the csv file into a pandas DataFrame
        end_time = time.time() 
            #records end time
        load_time = end_time - start_time 
            # calculates the time taken to load the file
        print(f"CSV file loaded succesfully in {load_time:.2f} seconds.")
        print(f"number of rows: {len(df)}") 
            # prints the number of rows in the DataFrame
        print(f"Columns: {df.columns.tolist()}") 
        df['order_date'] = pd.to_datetime(df['order_date'], format='%m/%d/%Y', errors='coerce')  # Convert order_date to datetime so all the same format.
        df.fillna(0, inplace=True)  
            # Fill NaN values with 0 for numeric columns
        df['sales'] = df['quantity'] * df['unit_price']  
            # Create a new 'sales' column as quantity * unit_price

        required_columns = ['quantity', 'unit_price', 'order_date'] # defining a list of required columns that should be present in the DataFrame
            # Checks if required columns are present
        missing_columns = [col for col in required_columns if col not in df.columns]
        if missing_columns:
            print(f"Warning: Missing required columns: {missing_columns}. Some analytics may not work properly without these columns.")    
        else: 
            print("All required columns are present.")

        return df
    
    except Exception as e: 
        # if there is an error while loading the file, it will be caught here and an error message will be printed
        print(f"Error loading CSV file: {e}")
        return None

# 1. FIRST FUNCTION IS DISPLAY_INITIAL_ROWS
def display_initial_rows(dataframe):
        # defining a function to display the initial rows of the DataFrame based on user input
    print("Enter rows to display:") 
    print(f"- Enter a number 1 to {len(dataframe)}") 
        # telling the user to enter a number between 1 and the total number of rows in the DataFrame
    print("- Enter 'all' to display all rows")
    print("- to skip preview, press Enter") 
        # telling the user to press Enter to skip the preview of the data
    user_input = input("Your choice: ").strip().lower() 
        # taking user input and stripping any whitespace and converting it to lowercase if user types "all" in uppercase

    if user_input == '':
        print("Skipping preview.")
        return
    elif user_input == 'all':
        print("Displaying all rows:")
        print(dataframe)
    elif user_input.isdigit and 1 <= int(user_input) <= len(dataframe): 
        # checking if the user input is a digit and within the valid range of row numbers
        print(f"Displaying first {user_input} rows:")
        print(dataframe.head(int(user_input))) 
        return dataframe.head(int(user_input))
            # if the user input is valid, it will display the specified number of rows using head() function
    else:
        print("Invalid input. Please try again.")
    # Quality Requirement: User Input Validation

# 2. SECOND FUNCTION IS SHOW TOTAL SALES BY REGION AND ORDER_TYPE USING PIVOT TABLE FUNCTION
def show_sales_by_region_and_order_type(dataframe):
    if 'sales_region' not in dataframe.columns or 'order_type' not in dataframe.columns or 'sales' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'sales_region', 'order_type', and 'sales' columns are present.")
        return
        # this function was generated by AI to check if required columns are present

    pivot_table = pd.pivot_table(dataframe, values='sales', index='sales_region', columns='order_type', aggfunc='sum', fill_value=0)
    # the pivot table will show the sales with region as the index and order type as the columns, with missing values filled with 0
    # the aggfunc='sum' will sum the sales for each region
    print("Total Sales by Region and Order Type:")
    print(pivot_table)
    return pivot_table

# 3. THIRD FUNCTION IS AVERAGE SALES BY REGION WITH AVERAGE SALES BY STATE AND SALE TYPE USING PIVOT TABLE FUNCTION
def show_average_sales_by_region_state_and_order_type(dataframe):
    if 'sales_region' not in dataframe.columns or 'customer_state' not in dataframe.columns or 'order_type' not in dataframe.columns or 'sales' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'sales_region', 'customer_state', 'order_type', and 'sales' columns are present.")
        return

    pivot_table = pd.pivot_table(dataframe, values='sales', index=['sales_region', 'customer_state'], columns='order_type', aggfunc='mean', fill_value=0)
    # the pivot table will show the sales with state as the region and state as the index and order type as the columns, with missing values filled with 0
    print("Average Sales by Region, State, and Order Type:")
    print(pivot_table)
    return pivot_table

# 4. FOURTH FUNCTION IS SALES BY CUSTOMER TYPE AND ORDER TYPE BY STATE USING PIVOT TABLE FUNCTION
def show_sales_by_customer_type_and_order_type_by_state(dataframe):
    if 'customer_state' not in dataframe.columns or 'customer_type' not in dataframe.columns or 'order_type' not in dataframe.columns or 'sales' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'customer_state', 'customer_type', 'order_type', and 'sales' columns are present.")
        return

    pivot_table = pd.pivot_table(dataframe, values='sales', index='customer_state', columns=['customer_type', 'order_type'], aggfunc='sum', fill_value=0)
    # the pivot table will show the sales with state as the index and customer type and order type as the columns, with missing values filled with 0
    print("Sales by Customer Type and Order Type by State:")
    print(pivot_table)
    return pivot_table

# 5. FIFTH FUNCTION IS TOTAL SALES QUANTITY AND PRICE BY REGION AND PRODUCT USING PIVOT TABLE FUNCTION
def show_total_sales_quantity_and_price_by_region_and_product(dataframe):
    if 'sales_region' not in dataframe.columns or 'product_category' not in dataframe.columns or 'sales' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'sales_region', 'product_category', and 'sales' columns are present.")
        return

    pivot_table = pd.pivot_table(dataframe, values=['sales', 'quantity'], index='sales_region', columns='product_category', aggfunc=sum, fill_value=0)
    # the pivot table will show the sales, quantity, with region as the index and product as the columns, with missing values filled with 0
    print("Total Sales and Quantity by Region and Product Category:")
    print(pivot_table)
    return pivot_table

# 6. SIXTH FUNCTION IS TOTAL SALES QUANTITY AND PRICE BY CUSTOMER TYPE AND PRODUCT USING PIVOT TABLE FUNCTION
def show_total_sales_quantity_and_price_by_customer_type_and_product(dataframe):
    if 'customer_type' not in dataframe.columns or 'product_category' not in dataframe.columns or 'sales' not in dataframe.columns or 'quantity' not in dataframe.columns or 'unit_price' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'customer_type', 'product_category', 'sales', 'quantity', and 'unit_price' columns are present.")
        return
    
    pivot_table = pd.pivot_table(dataframe, values=['sales', 'quantity'], index=['customer_type', 'order_type'], columns='product_category', aggfunc=sum, fill_value=0)
    # the pivot table will show the sales, quantity, with customer type and order type as the index and product as the columns, with missing values filled with 0
    print("Total Sales and Quantity by Customer, Order Type and Product Category:")
    print(pivot_table)
    return pivot_table

# 7. SEVENTH FUNCTION IS MAX AND MIN SALES PRICE BY CATEGORY USING PIVOT TABLE FUNCTION
def show_max_and_min_sales_price_by_category(dataframe):
    if 'product_category' not in dataframe.columns or 'sales' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'product_category' and 'sales' columns are present.")
        return

    pivot_table = pd.pivot_table(dataframe, values='sales', index='product_category', aggfunc=['max', 'min'], fill_value=0)
    # the pivot table will show the max and min sales with category as the index, with missing values filled with 0
    # aggfunc=['max', 'min'] will automatically calculate the maximum and minimum sales for each category
    print("Max and Min Sales Price by Category:")
    print(pivot_table)
    return pivot_table

# 8. EIGHTH FUNCTION IS NUMBER OF UNIQUE EMPLOYEES BY REGION USING PIVOT TABLE FUNCTION
def show_employees_by_region(dataframe):
    if 'sales_region' not in dataframe.columns or 'employee_id' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'sales_region' and 'employee_id' columns are present.")
        return

    pivot_table = pd.pivot_table(dataframe, values='employee_id', index='sales_region', aggfunc=pd.Series.nunique)
    # the pivot table will show the number of unique employees with sales region as the index
    # this line of code was generated by AI using the prompt 'How do I use Pandas to count unique values in a column?'
    # it numbers the unique employee IDs in the employee_id column of the DataFrame.
    pivot_table.columns = ['Number of Employees'] 
        # renaming the column to "Number of Employees"
    print("\nNumber of employees by region:")
    print(pivot_table)
    return pivot_table

# 9. NINTH FUNCTION IS SHOW SALES BY REGION AND PRODUCT, WITH PERCENTAGE OF QUANTITY ANDTOTAL SALES USING PIVOT TABLE FUNCTION
# INDIVIDUAL REQUIREMENT 8: Add an analytic that shows sales by region, product, showing the percentage of the quantity and total sales per region and product.
def show_sales_by_region_and_product_with_percentage(dataframe):
    if 'sales_region' not in dataframe.columns or 'product_category' not in dataframe.columns or 'sales' not in dataframe.columns or 'quantity' not in dataframe.columns:
        print("Error: Required columns for this analysis are missing. Please ensure 'sales_region', 'product_category', 'sales', and 'quantity' columns are present.")
        return

    pivot_table = pd.pivot_table(dataframe, values=['sales', 'quantity'], index='sales_region', columns='product_category', aggfunc='sum', fill_value=0)
    # the pivot table will show the sales with region as the index and product category as the columns, with missing values filled with 0
    pivot_table[('sales', 'Total')] = pivot_table['sales'].sum(axis=1)
    pivot_table[('quantity', 'Total')] = pivot_table['quantity'].sum(axis=1)
        # this code adds a new column to the pivot table called 'Total' under the sales and quantity groups.
        # it sums the sales and quantity across the category columns for the same region.
    for column in pivot_table['sales'].columns:
        pivot_table[('sales', column + ' % of Total')] = (
            (pivot_table[('sales', column)] / pivot_table[('sales', 'Total')]) * 100).round(2).astype(str) + '%'
    for column in pivot_table['quantity'].columns:
        pivot_table[('quantity', column + ' % of Total')] = (
            (pivot_table[('quantity', column)] / pivot_table[('quantity', 'Total')]) * 100).round(2).astype(str) + '%'
    # add the quantity percentage columns by iterating through each category column in the pivot table (except for the 'Total Sales' column) and calculating the percentage of total sales for each category, rounding to 2 decimal places, and adding a '%' sign to the end of the value.
    
    # this loop iterates through every value in the pivot table except for the 'Total Sales' column.
    # it divides the column by total sales to get the percentage.
    print("Sales by Region and Product Category, with Percentage of Total Sales:")
    print(pivot_table)
    return pivot_table

# 10. TENTH FUNCTION IS CREATE CUSTOM PIVOT TABLE BASED ON USER INPUT
def create_custom_pivot_table(dataframe):
    print("Create a Custom Pivot Table")
    for i, col in enumerate(dataframe.columns, start=1):
        print(f"{i}. {col}")

    while True:
        print("Select the row(s) for the pivot table:")
        print("1. Employee Name")
        print("2. Sales Region")
        print("3. Product Category")

        rows_input = input("Enter the number(s) of your choice(s), separated by commas: ")
        rows_cols = [col.strip() for col in rows_input.split(",")]
        if not all(col in ['1', '2', '3'] for col in rows_cols):
            print("Invalid input. Please enter one of the following options for rows: 1, 2, or 3.")
        else:
            break
    
    if rows_cols == ['1']:
        rows_cols = ['employee_name']
    elif rows_cols == ['2']:
        rows_cols = ['sales_region']
    elif rows_cols == ['3']:
        rows_cols = ['product_category']
    
    while True:
        print("Select the column(s) (optional) for the pivot table:")
        print("1. Order Type")
        print("2. Customer Type")
        print("- Press Enter to skip columns")
        cols_input = input("Enter the number(s) of your choice(s), separated by commas: ")
        if cols_input.strip() == '':
            cols_cols = None
            break
        cols_cols = [col.strip() for col in cols_input.split(",")]
        if not all(col in ['1', '2'] for col in cols_cols):
            print("Invalid input. Please enter one of the following options for columns: 1, 2, or enter for no columns.")
        else:
            break
    
    if cols_cols == ['1']:
        cols_cols = ['order_type']
    elif cols_cols == ['2']:
        cols_cols = ['customer_type']
    elif cols_cols is None:
        cols_cols = None

    while True: 
        print("Select values:")
        print("1. Quantity")
        print("2. Sales Price")
        values_input = input("Enter the number(s) of your choice(s), separated by commas: ")
        values_cols = [col.strip() for col in values_input.split(",")]
        if not all(col in ['1', '2'] for col in values_cols):
            print("Invalid input. Please enter one of the following options for values: 1 or 2.")
        else:
            break
    
    if values_cols == ['1']:
        values_cols = ['quantity']
    elif values_cols == ['2']:
        values_cols = ['sales']

    print("Select aggregation function:")
    print("1. sum")
    print("2. mean")
    print("3. count")
    while True:
        aggfunc_input = input("Enter your choice (1, 2, or 3): ")
        if aggfunc_input not in ['1', '2', '3']:
            print("Invalid aggregation function. Please enter 1, 2, or 3.")
        else:
            break
    
    if aggfunc_input == '1':
        aggfunc_input = 'sum'
    elif aggfunc_input == '2':
        aggfunc_input = 'mean'
    elif aggfunc_input == '3':
        aggfunc_input = 'count'

    try:
        pivot_table = pd.pivot_table(dataframe, values=values_cols, index=rows_cols, columns=cols_cols, aggfunc=aggfunc_input, fill_value=0)
        print("Custom Pivot Table:")
        print(pivot_table)
        return pivot_table
    except Exception as e:
        print(f"Error creating pivot table: {e}")

# 10. TENTH FUNCTION IS EXIT PROGRAM
def exit_program(dataframe):
    print("Exiting the program. Goodbye!")
    exit(0) # this function will print a goodbye message and exit the program when called



# create dashboard menu with dashboard functions
def display_menu(dataframe):
    menu_options = (
        ("Show the first n rows of sales data", display_initial_rows),
        ("Show total sales by region and order type", show_sales_by_region_and_order_type),
        ("Show average sales by region, state, and order type", show_average_sales_by_region_state_and_order_type),
        ("Show sales by customer type and order type by state", show_sales_by_customer_type_and_order_type_by_state),
        ("Show total sales and quantity by region and product", show_total_sales_quantity_and_price_by_region_and_product),
        ("Show total sales and quantity by customer type and order type", show_total_sales_quantity_and_price_by_customer_type_and_product),
        ("Show maximum and minimum sales price by category", show_max_and_min_sales_price_by_category),
        ("Show number of unique employees by region", show_employees_by_region),
        ("Show sales by region and product, with percentage of total sales", show_sales_by_region_and_product_with_percentage),
        ("Create a custom pivot table", create_custom_pivot_table),
        ("Exit", exit_program)
    )

    print("\nAvailable options:")
    for i, (description, _) in enumerate(menu_options, start=1):
        print(f"{i}. {description}")

    try:
        menu_len = len(menu_options)
        choice = int(input(f"Enter your choice (1-{menu_len}): "))
        if 1 <= choice <= menu_len:
            action = menu_options[choice - 1][1]
            result = action(dataframe)
            save_to_excel = input("Would you like these results to be saved to an Excel file? (Y/N): ").strip().upper()
            # INDIVIDUAL REQUIREMENT 1: For each result, ask the user if they want the results exported to an Excel file.
            # strip.upper() will change the user input to uppercase in case
            if save_to_excel == 'Y':
                filename = input("Enter the filename (without the .xlsx extension): ").strip()
                try:
                    result.to_excel(f"{filename}.xlsx")
                    print(f"Results saved to {filename}.xlsx successfully.")
                except Exception as e:
                    print(f"Error saving to Excel file: {e}")
            elif save_to_excel == 'N':
                print("Results will not be saved.")
            # this code was partly generated by AI with the prompt 'How would I go about saving the data to an Excel file in Python?'
        else:
            print("Invalid choice. Please enter a number corresponding to the options.")

    except ValueError:
        print("Invalid input. Please enter a number corresponding to the options.")

sales_data = load_csv(filename)

def main():
    while True:
        print("Sales Data Dashboard")
        display_menu(sales_data)

if __name__ == "__main__":
    main()