# Name: Cassiddy Ginoza
# I had requirements 1 and 8, which were documented as comments in the quiz.html file, and 
# in this A3.py file. I also documented the functional requirements in these files as well.

from flask import Flask, render_template, request, redirect, url_for, session, jsonify
    # session is used to temporarily keep track of a user's progress 
import json
import random
    # random is used to shuffle the questions.
import time

def load_users():
    try:
        with open("users.json", "r") as f:
            return json.load(f)
    except:
        return {}

def save_users(users):
    with open("users.json", "w") as f:
        json.dump(users, f, indent=4)
 
app = Flask(__name__)
app.secret_key = "secret" 

USERS = load_users()

with open("south_park_questions.json", "r") as f:
    questions = json.load(f)

# REQUIREMENT: ERROR HANDLING AND VALIDATION
@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        userid = request.form['username']
        password = request.form['password']

        users = load_users() 

        if userid in users and users[userid]["password"] == password:
            session['user'] = userid
            return redirect(url_for('quiz'))
        else:
            return "Invalid username or password."
        # ERROR HANDLING: returns an error message if the username or password doesn't match the
        # informaion in the users.json file.

    return render_template('login.html')

# REQUIREMENT: ERROR HANDLING AND VALIDATION
@app.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        userid = request.form['username']
        password = request.form['password']

        users = load_users()

        if userid in users:
            return "Username already exists."
        #ERROR HANDLING: if the username already exists, it will return an error message.

        users[userid] = {
            "password": password,
            "history": []
        }
        # this code adds the new user's information to the users dictionary, then to the users.json file.

        save_users(users)
        # this code allows for the user to append their username and password to the users.json file.
        # FIX: this line is required so the new user is actually stored in the JSON file.

        return redirect(url_for('login'))
        # this code redirects the user to the login page, so they can log in with their account
        # after they register.

    return render_template('register.html')
# this code was generated by AI, using the prompt "How do I fix the original code so that users
# can add their own username and password to the json file?"

# REQUIREMENT: BACKEND REQUIREMENTS: this code implements a RESTful API which retrieves the quiz questions.
@app.route("/api/questions", methods=["GET"])
def api_get_questions():
    return jsonify(questions)


@app.route('/')
def home():
    return render_template('index.html')

@app.route('/quiz', methods=['GET', 'POST'])
def quiz():
    if 'user' not in session:
        return redirect(url_for('login'))

    user = session.get("user")
    users = load_users()

    user_history = users.get(user, {}).get("history", [])

    if "start_time" not in session:
        session["start_time"] = time.time()

    if "index" not in session or "question_order" not in session:
        # this code initializes a session for the user if it's their first time accessing.
        session["index"] = 0
        # index is the question number.
        session["score"] = 0
        # score is the correct answers user answers.
        session["question_order"] = list(range(len(questions)))
        random.shuffle(session["question_order"])
        # this code was created by AI, using the prompt "How would I use random in order to shuffle the questions for the user?"
         # QUESTION DISPLAY REQUIREMENTS: this code randomizes the question order so that the user doesn't get the same order for 
        # questions each time.

    if session["index"] >= len(questions):
        return redirect(url_for("result"))
        # this code will end and redirect to result if index is equal to length of questions

    # ASSIGNED REQUIREMENT 8: Include a progress bar to visually represent quiz completion status
    progress = (session["index"] / len(questions)) * 100

    if request.method == "POST": # user submits an answer from the page
        if "next" in request.form:
            session["index"] += 1

            session.pop("explanation", None)
            session.pop("result", None)

            if session["index"] >= len(questions):
                return redirect(url_for("result"))

        else:
            # compares user's answer to correct answer from the list.
            user_answer = request.form.get("answer")

            if user_answer:
                q_index = session["question_order"][session["index"]]
                current_q = questions[q_index]

                # if the user submits an answer, it will retrieve the question from the
                # questions list by its index.
                if user_answer == current_q["answer"]:
                    session["score"] += 1
                    # if the answer matches the current question, the session adds 1 to the score.
                    session["result"] = "Correct!"
                else:
                    session["result"] = "Wrong."

                session["explanation"] = current_q["explanation"]
                # SCORE TRACKING AND FEEDBACK: this code provides an explanation for the answer despite whether the answer is correct.

    q_index = session["question_order"][session["index"]]
    q = questions[q_index]

    choices = q["choices"][:]
    random.shuffle(choices)
    # this code was created by AI, using the prompt "How would I use random to shuffle the choices for each question?"
    # QUESTION DISPLAY REQUIREMENTS: this code randomizes the choice so that the user doesn't get the same order for 
    # choices each time.

    return render_template(
        "quiz.html",
        question=q,
        choices=choices,
        explanation=session.get("explanation"),
        result=session.get("result"),
        progress=progress,
        user=user,
        history=user_history[-5:],
        show_history=session.get("index", 0) == 0
    )

# REQUIREMENT: BACKEND REQUIREMENTS: this code implements a RESTful API which stores the user's score after
# the quiz is completed.
@app.route("/api/score", methods=["POST"])
def api_save_score():
    data = request.get_json()  # gets JSON data from request

    username = data.get("username")
    score = data.get("score")

    users = load_users()

    if not username or score is None:
        return jsonify({"error": "Missing username or score"}), 400

    if username in users:
        users[username]["history"].append(score)
        save_users(users)
        return jsonify({"message": "Score saved successfully"}), 200
    else:
        return jsonify({"error": "User not found"}), 404
    # this code was partially created by AI, using the prompt "How do I implement a restful API for storing user errors?"

@app.route("/result")
def result():
    # Get score from session and render result page
    score = session.get("score", 0)
    start_time = session.get("start_time", 0)
    end_time = time.time()
    total_time = end_time - start_time
    total_time = round(total_time, 2) 
    # SCORE TRACKING AND FEEDBACK: This code calculates the time taken from the beginning to the end of the
    # quiz.
    
    user = session.get("user")
    users = load_users()

    history = []

    if user is not None and user in users:
        history = users[user].get("history", [])
    # this code gets the user's history so it can be displayed on the results.

    users[user]["history"].append(score)
    # this code needed to be altered in order to save the user's score history in the users.json
    # file.
    save_users(users)

    session.clear()  # Clear session after showing result
    return render_template(
        "result.html",
        score=score,
        total=len(questions),
        total_time=total_time,
        history=history
    )
def main():
    app.run(debug=True)

if __name__ == "__main__":
    main()